---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/services
#
- Home:
    - Home Assistant:
        icon: home-assistant
        href: http://192.168.1.19:8123
        ping: http://192.168.1.19:8123
    - Jellyfin:
        icon: jellyfin
        href: http://192.168.1.19:8096
        ping: http://192.168.1.19:8096
    - Nextcloud:
        icon: nextcloud
        href: http://nextcloud.nlab.casa
        ping: http://nextcloud.nlab.casa
    - Pterodactyl:
        icon: pterodactyl
        href: http://ptero.nlab.casa
        ping: http://ptero.nlab.casa

- System:
    - Portainer:
        icon: portainer
        href: http://192.168.1.19:9000
        ping: http://192.168.1.19:9000
#        widget:
#            type: portainer
#            url: https://192.168.1.19:9000
#            env: 2
#            key: 
    - Dozzle: 
        icon: dozzle
        href: http://192.168.1.19:9999
        ping: http://192.168.1.19:9999
    - Grafana: 
        icon: grafana
        href: http://192.168.1.19:3000
        ping: http://192.168.1.19:3000
    - cAdvisor: 
        icon: cadvisor
        href: http://192.168.1.19:8080
        ping: http://192.168.1.19:8080
    - Prometheus:
        icon: prometheus
        href: http://192.168.1.19:9090
        ping: http://192.168.1.19:9090
        widget:
            type: prometheus
            url: http://192.168.1.19:9090
    - Glances:
        icon: glances
        href: http://192.168.1.19:61208
        ping: http://192.168.1.19:61208

- Network:
    - Router:
        icon: router
        href: http://192.168.1.1
        ping: http://192.168.1.1
    - Speedtest Tracker:
        icon: speedtest-tracker
        href: http://192.168.1.19:8081
        ping: http://192.168.1.19:8081
        widget:
            type: speedtest
            url: http://192.168.1.19:8081
    - NGINX Proxy Manager:
        icon: nginx-proxy-manager
        href: http://192.168.1.19:81
        ping: http://192.168.1.19:81
        server: docker #setup in docker.yaml
        container: nginxproxymanager
        widget:
            type: npm
            url: http://192.168.1.19:81
            username: bnexcess@gmail.com
            password: bnexcess
    - Uptime Kuma:
        icon: uptime-kuma
        href: http://192.168.1.19:3001
        ping: http://192.168.1.19:3001
        widget:
            type: uptimekuma
            url: http://192.168.1.19:3001
            slug: docker
    # pihole

# These are all integrated through Glances
- Metrics: 
    - System Information:
        widget: 
            type: glances
            url: http://192.168.1.19:61208
            metric: info
    - CPU Usage:
        widget:
            type: glances
            url: http://192.168.1.19:61208
            metric: cpu
    - Network Usage:
        widget:
            type: glances
            url: http://192.168.1.19:61208
            metric: network:eth0
    - Memory Usage:
        widget: 
            type: glances
            url: http://192.168.1.19:61208
            metric: memory
    - Top Processes:
        widget: 
            type: glances
            url: http://192.168.1.19:61208
            metric: process
    - CPU Temperature:
        widget: 
            type: glances
            url: http://192.168.1.19:61208
            metric: sensor:cpu
    - Disk I/O:
        widget: 
            type: glances
            url: http://192.168.1.19:61208
            metric: disk:sbd #temp
    - Disk Usage 1:
        widget:
            type: glances
            url: http://192.168.1.19:61208
            metric: fs:/
    - Disk Usage 2:
        widget:
            type: glances
            url: http://192.168.1.19:61208
            metric: fs:/media/drive2