---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/services
#
- main-apps:
    - Home Assistant:
        icon: home-assistant
        href: https://hass.nlab.casa/
        ping: http://192.168.1.19:8123
        description: 8123
    - Jellyfin:
        icon: jellyfin
        href: https://jellyfin.nlab.casa/
        ping: http://192.168.1.19:8096
        description: 8096
    - Nextcloud:
        icon: nextcloud
        href: https://nextcloud.nlab.casa/login
        ping: http://192.168.1.19:8484
        description: 8484

- other-apps:
    - Portainer:
        icon: portainer
        href: https://portainer.nlab.casa/
        ping: http://192.168.1.19:9000
        description: 9000
#        widget:
#            type: portainer
#            url: https://portainer.nlab.casa/
#            env: 2
#            key: 
    - Grafana: 
        icon: grafana
        href: https://grafana.nlab.casa/login
        ping: http://192.168.1.19:3000
        description: 3000
    - Glances:
        icon: glances
        href: https://glances.nlab.casa/
        ping: http://192.168.1.19:61208
        description: 61208
    - Router:
        icon: router
        href: https://router.nlab.casa/
        ping: http://192.168.1.1
        description: BE9300
    - Dozzle: 
        icon: dozzle
        href: https://dozzle.nlab.casa/
        ping: http://192.168.1.19:9999
        description: 9999
    - File Browser: 
        icon: filebrowser
        href: https://file.nlab.casa/
        ping: http://192.168.1.19:8383
        description: 8383
    - cAdvisor: 
        icon: cadvisor
        href: https://cadvisor.nlab.casa/
        ping: http://192.168.1.19:8080
        description: 8080
    - Pi-hole:
        icon: pi-hole
        href: https://pi.nlab.casa/admin/
        ping: http://192.168.1.19:86
        description: 86
    - Prowlarr:
        icon: prowlarr
        href: https://prowlarr.nlab.casa/
        ping: http://192.168.1.19:9696
        description: 9696
    - Radarr:
        icon: radarr
        href: https://radarr.nlab.casa/
        ping: http://192.168.1.19:7878
        description: 7878
    - Sonarr:
        icon: sonarr
        href: https://sonarr.nlab.casa/
        ping: http://192.168.1.19:8989
        description: 8989
    - SABnzbd:
        icon: sabnzbd
        href: https://sabnzbd.nlab.casa/
        ping: http://192.168.1.19:8181
        description: 8181   

- has-widget:
    - Minecraft:
        icon: minecraft
        href: https://rcon.nlab.casa
        ping: http://192.168.1.19:4326
        description: 4326
        widget:
            type: minecraft
            url: udp://192.168.1.19:25565
    - Uptime Kuma:
        icon: uptime-kuma
        href: https://uptime.nlab.casa/
        ping: http://192.168.1.19:3001
        description: 3001
        widget:
            type: uptimekuma
            url: https://uptime.nlab.casa/
            slug: docker
    - What's up Docker?:
        icon: whats-up-docker-light
        href: https://wud.nlab.casa/
        ping: http://192.168.1.19:3535
        description: 3535
        widget:
            type: whatsupdocker
            url: https://wud.nlab.casa/
    - Speedtest Tracker:
        icon: speedtest-tracker
        href: https://speedtest.nlab.casa/
        ping: http://192.168.1.19:8081
        description: 8081
        widget:
            type: speedtest
            url: https://speedtest.nlab.casa/
            bitratePrecision: 0
    - Prometheus:
        icon: prometheus
        href: https://prometheus.nlab.casa/
        ping: http://192.168.1.19:9090
        description: 9090
        widget:
            type: prometheus
            url: https://prometheus.nlab.casa/
    - NGINX Proxy Manager:
        icon: nginx-proxy-manager
        href: https://nginx.nlab.casa/
        ping: http://192.168.1.19:81
        description: 81
        # server: docker #setup in docker.yaml
        # container: nginxproxymanager
        widget:
            type: npm
            url: https://nginx.nlab.casa/
            username: bnexcess@gmail.com
            password: bnexcess

# >>>>These are all integrated through Glances<<<<
#- Metrics: 
    #- System Information:
    #    widget: 
    #        type: glances
    #        url: http://192.168.1.19:61208
    #        metric: info
    #        chart: false
#    - CPU:
#        widget:
#            type: glances
#            url: http://192.168.1.19:61208
#            metric: cpu
#            chart: false
#    - Network Usage:
#        widget:
#            type: glances
#            version: 4
#            url: http://192.168.1.19:61208
#            metric: network:enp2s0
#            chart: true
#    - Memory:
#        widget: 
#            type: glances
#            url: http://192.168.1.19:61208
#            metric: memory
#            chart: false
#    - Top Processes:
#        widget: 
#            type: glances
#            version: 4
#            url: http://192.168.1.19:61208
#            metric: process
#            chart: true
    #- CPU Temperature:
    #    widget: 
    #        type: glances
    #        url: http://192.168.1.19:61208
    #        metric: sensor:cpu
#    - Drive1 I/O:
#        widget: 
#            type: glances
#            version: 4
#            url: http://192.168.1.19:61208
#            metric: disk:nvme0n1
#            chart: true
#    - Drive2 I/O:
#        widget: 
#            type: glances
#            version: 4
#            url: http://192.168.1.19:61208
#            metric: disk:nvme1n1
#            chart: true
#    - Drive 1:
#        widget:
#            type: glances
#            url: http://192.168.1.19:61208
#            metric: fs:/
#            chart: false
#    - Drive 2:
#        widget:
#            type: glances
#            url: http://192.168.1.19:61208
#            metric: fs:/media/drive2
#            chart: false