---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/services
#
- Home:
    - Home Assistant:
        icon: home-assistant
        href: http://192.168.1.19:8123
        ping: http://192.168.1.19:8123
    - Nextcloud:
        icon: nextcloud
        href: https://nextcloud.nlab.casa/login
        ping: https://nextcloud.nlab.casa/login
    - Actual Budget:
        icon: actual
        href: https://actual.nlab.casa
        ping: https://actual.nlab.casa
    - Jellyfin:
        icon: jellyfin
        href: http://192.168.1.19:8096
        ping: http://192.168.1.19:8096
    - Prowlarr:
        icon: prowlarr
        href: http://192.168.1.19:9696
        ping: http://192.168.1.19:9696
    - Radarr:
        icon: radarr
        href: http://192.168.1.19:7878
        ping: http://192.168.1.19:7878
    - Sonarr:
        icon: sonarr
        href: http://192.168.1.19:8989
        ping: http://192.168.1.19:8989
    - SABnzbd:
        icon: sabnzbd
        href: http://192.168.1.19:8181
        ping: http://192.168.1.19:8181
- System:
    - Portainer:
        icon: portainer
        href: http://192.168.1.19:9000
        ping: http://192.168.1.19:9000
#        widget:
#            type: portainer
#            url: https://192.168.1.19:9000
#            env: 2
#            key: 
    - What's up Docker?:
        icon: wud-light
        href: http://192.168.1.19:3535
        ping: http://192.168.1.19:3535
        widget:
            type: whatsupdocker
            url: http://192.168.1.19:3535
    - Dozzle: 
        icon: dozzle
        href: http://192.168.1.19:9999
        ping: http://192.168.1.19:9999
    - File Browser: 
        icon: filebrowser
        href: http://192.168.1.19:8383
        ping: http://192.168.1.19:8383
    - Grafana: 
        icon: grafana
        href: http://192.168.1.19:3000
        ping: http://192.168.1.19:3000
    - cAdvisor: 
        icon: cadvisor
        href: http://192.168.1.19:8080
        ping: http://192.168.1.19:8080
    - Prometheus:
        icon: prometheus
        href: http://192.168.1.19:9090
        ping: http://192.168.1.19:9090
        widget:
            type: prometheus
            url: http://192.168.1.19:9090
    - Glances:
        icon: glances
        href: http://192.168.1.19:61208
        ping: http://192.168.1.19:61208

- Network:
    - Router:
        icon: router
        href: http://192.168.1.1
        ping: http://192.168.1.1
    - Pi-hole:
        icon: pi-hole
        href: http://192.168.1.19:86/admin
        ping: http://192.168.1.19:86/admin
    - Speedtest Tracker:
        icon: speedtest-tracker
        href: http://192.168.1.19:8081
        ping: http://192.168.1.19:8081
        widget:
            type: speedtest
            url: http://192.168.1.19:8081
            bitratePrecision: 0
    - NGINX Proxy Manager:
        icon: nginx-proxy-manager
        href: http://192.168.1.19:81
        ping: http://192.168.1.19:81
        # server: docker #setup in docker.yaml
        # container: nginxproxymanager
        widget:
            type: npm
            url: http://192.168.1.19:81
            username: bnexcess@gmail.com
            password: bnexcess
    - Uptime Kuma:
        icon: uptime-kuma
        href: http://192.168.1.19:3001
        ping: http://192.168.1.19:3001
        widget:
            type: uptimekuma
            url: http://192.168.1.19:3001
            slug: docker
#    - Pterodactyl:
#        icon: pterodactyl
#        href: http://ptero.nlab.casa
#        ping: http://ptero.nlab.casa

# These are all integrated through Glances
- Metrics: 
    #- System Information:
    #    widget: 
    #        type: glances
    #        url: http://192.168.1.19:61208
    #        metric: info
    #        chart: false
    #- CPU Usage:
    #    widget:
    #        type: glances
    #        url: http://192.168.1.19:61208
    #        metric: cpu
    - Network Usage:
        widget:
            type: glances
            version: 4
            url: http://192.168.1.19:61208
            metric: network:enp2s0
            chart: true
    #- Memory Usage:
    #    widget: 
    #        type: glances
    #        url: http://192.168.1.19:61208
    #        metric: memory
    - Top Processes:
        widget: 
            type: glances
            version: 4
            url: http://192.168.1.19:61208
            metric: process
            chart: true
    #- CPU Temperature:
    #    widget: 
    #        type: glances
    #        url: http://192.168.1.19:61208
    #        metric: sensor:cpu
    - Drive1 I/O:
        widget: 
            type: glances
            version: 4
            url: http://192.168.1.19:61208
            metric: disk:nvme0n1
            chart: true
    - Drive2 I/O:
        widget: 
            type: glances
            version: 4
            url: http://192.168.1.19:61208
            metric: disk:nvme1n1
            chart: true
    #- Disk Usage 1:
    #    widget:
    #        type: glances
    #        url: http://192.168.1.19:61208
    #        metric: fs:/
    #- Disk Usage 2:
    #    widget:
    #        type: glances
    #        url: http://192.168.1.19:61208
    #        metric: fs:/media/drive2