---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/services
#
- Minerva:
    - Home Assistant:
        icon: home-assistant
        href: https://hass.nlab.casa/
        ping: https://hass.nlab.casa/
        description: 8123
    - Jellyfin:
        icon: jellyfin
        href: https://jellyfin.nlab.casa/
        ping: https://jellyfin.nlab.casa/
        description: 8096
    - Nextcloud:
        icon: nextcloud
        href: https://nextcloud.nlab.casa/login
        ping: https://nextcloud.nlab.casa/login
        description: 8484
    - Dozzle: 
        icon: dozzle
        href: https://dozzle.nlab.casa/
        ping: https://dozzle.nlab.casa/
        description: 9999
    - Grafana: 
        icon: grafana
        href: https://grafana.nlab.casa/login
        ping: https://grafana.nlab.casa/login
        description: 3000
    - Portainer:
        icon: portainer
        href: https://portainer.nlab.casa/
        ping: https://portainer.nlab.casa/
        description: 9000
#        widget:
#            type: portainer
#            url: https://portainer.nlab.casa/
#            env: 2
#            key: 
    

#    - Actual Budget:
#        icon: actual
#        href: https://actual.nlab.casa
#        ping: https://actual.nlab.casa
    
- System:
    - What's up Docker?:
        icon: whats-up-docker-light
        href: https://wud.nlab.casa/
        ping: https://wud.nlab.casa/
        description: 3535
        widget:
            type: whatsupdocker
            url: https://wud.nlab.casa/
    - File Browser: 
        icon: filebrowser
        href: https://file.nlab.casa/
        ping: https://file.nlab.casa/
        description: 8383
    - cAdvisor: 
        icon: cadvisor
        href: https://cadvisor.nlab.casa/
        ping: https://cadvisor.nlab.casa/
        description: 8080
    - Prometheus:
        icon: prometheus
        href: https://prometheus.nlab.casa/
        ping: https://prometheus.nlab.casa/
        description: 9090
        widget:
            type: prometheus
            url: https://prometheus.nlab.casa/
    - Glances:
        icon: glances
        href: https://glances.nlab.casa/
        ping: https://glances.nlab.casa/
        description: 61208
        
- Network:
    - Router:
        icon: router
        href: https://router.nlab.casa/
        ping: https://router.nlab.casa/
        description: BE9300
    - NGINX Proxy Manager:
        icon: nginx-proxy-manager
        href: https://nginx.nlab.casa/
        ping: https://nginx.nlab.casa/
        description: 81
        # server: docker #setup in docker.yaml
        # container: nginxproxymanager
        widget:
            type: npm
            url: https://nginx.nlab.casa/
            username: bnexcess@gmail.com
            password: bnexcess
    - Pi-hole:
        icon: pi-hole
        href: https://pi.nlab.casa/admin/
        ping: https://pi.nlab.casa/admin/
        description: 86
    - Speedtest Tracker:
        icon: speedtest-tracker
        href: https://speedtest.nlab.casa/
        ping: https://speedtest.nlab.casa/
        description: 8081
        widget:
            type: speedtest
            url: https://speedtest.nlab.casa/
            bitratePrecision: 0
    - Uptime Kuma:
        icon: uptime-kuma
        href: https://uptime.nlab.casa/
        ping: https://uptime.nlab.casa/
        description: 3001
        widget:
            type: uptimekuma
            url: https://uptime.nlab.casa/
            slug: docker
#    - Pterodactyl:
#        icon: pterodactyl
#        href: http://ptero.nlab.casa
#        ping: http://ptero.nlab.casa

- Media:
    - Prowlarr:
        icon: prowlarr
        href: https://prowlarr.nlab.casa/
        ping: https://prowlarr.nlab.casa/
        description: 9696
    - Radarr:
        icon: radarr
        href: https://radarr.nlab.casa/
        ping: https://radarr.nlab.casa/
        description: 7878
    - Sonarr:
        icon: sonarr
        href: https://sonarr.nlab.casa/
        ping: https://sonarr.nlab.casa/
        description: 8989
    - SABnzbd:
        icon: sabnzbd
        href: https://sabnzbd.nlab.casa/
        ping: https://sabnzbd.nlab.casa/
        description: 8181


# >>>>These are all integrated through Glances<<<<
- Metrics: 
    #- System Information:
    #    widget: 
    #        type: glances
    #        url: http://192.168.1.19:61208
    #        metric: info
    #        chart: false
    - CPU:
        widget:
            type: glances
            url: http://192.168.1.19:61208
            metric: cpu
            chart: false
#    - Network Usage:
#        widget:
#            type: glances
#            version: 4
#            url: http://192.168.1.19:61208
#            metric: network:enp2s0
#            chart: true
    - Memory:
        widget: 
            type: glances
            url: http://192.168.1.19:61208
            metric: memory
            chart: false
#    - Top Processes:
#        widget: 
#            type: glances
#            version: 4
#            url: http://192.168.1.19:61208
#            metric: process
#            chart: true
    #- CPU Temperature:
    #    widget: 
    #        type: glances
    #        url: http://192.168.1.19:61208
    #        metric: sensor:cpu
#    - Drive1 I/O:
#        widget: 
#            type: glances
#            version: 4
#            url: http://192.168.1.19:61208
#            metric: disk:nvme0n1
#            chart: true
#    - Drive2 I/O:
#        widget: 
#            type: glances
#            version: 4
#            url: http://192.168.1.19:61208
#            metric: disk:nvme1n1
#            chart: true
    - Drive 1:
        widget:
            type: glances
            url: http://192.168.1.19:61208
            metric: fs:/
            chart: false
    - Drive 2:
        widget:
            type: glances
            url: http://192.168.1.19:61208
            metric: fs:/media/drive2
            chart: false