---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings
#

title: Minerva
headerStyle: clean
statusStyle: dot
showStats: true
favicon: /images/icon_minerva.png
background: 
    image: /images/background_redgalaxy.png
    opacity: 0.2
theme: dark
color: gray
quicklaunch:
    searchDescriptions: true
    hideInternetSearch: true
    hideVisitURL: false
target: _blank
hideVersion: true
language: en
#providers:
#  openweathermap: openweathermapapikey
#  weatherapi: weatherapiapikey

layout:
    small-apps:
        style: row
        columns: 4
        useEqualHeights: true
        header: false
    grpA:
        style: row
        columns: 2
        header: false
        media:
            style: row
            columns: 2
            header: false
        wide:
            header: false

