---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings
#

base: http://192.168.1.19:3002

headerStyle: underlined

title: Bryan's WIP Homepage

background: https://cdn.discordapp.com/attachments/337320584084062208/1098469548916744212/13u5ew9elt191.png
backgroundOpacity: 0.2

#layout:
#  System:
#    style: row
#    columns: 4

# theme: dark
# color: slate
# favicon: https://www.google.com/favicon.ico

quicklaunch:
    searchDescriptions: true
    hideInternetSearch: true
    hideVisitURL: false

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

target: _blank
hideVersion: true
language: en