---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings
#

base: https://nlab.casa

headerStyle: boxed

title: Minerva

background: /app/config/background_redgalaxy.png
backgroundOpacity: 0.2

#layout:
#  System:
#    style: row
#    columns: 4

theme: dark
color: neutral

favicon: /app/config/icon_minerva.png

quicklaunch:
    searchDescriptions: true
    hideInternetSearch: true
    hideVisitURL: false

#providers:
#  openweathermap: openweathermapapikey
#  weatherapi: weatherapiapikey

target: _blank
hideVersion: true
language: en