---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings
#

base: http://192.168.1.19:3002

headerStyle: underlined

title: Minerva

background: https://cdn.discordapp.com/attachments/337320584084062208/1098487762681872444/mdh54ilu39g81.png
backgroundOpacity: 0.1

#layout:
#  System:
#    style: row
#    columns: 4

# theme: dark
# color: slate

favicon: https://icons8.com/icon/fMjAGSWjl4B0/m-key

quicklaunch:
    searchDescriptions: true
    hideInternetSearch: true
    hideVisitURL: false

#providers:
#  openweathermap: openweathermapapikey
#  weatherapi: weatherapiapikey

target: _blank
hideVersion: true
language: en