---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings
#

headerStyle: boxed

title: Minerva

background: /images/background_redgalaxy.png
backgroundOpacity: 0.2


layout:
    Home:
    System:
    Network:
    
#lock Metrics section to 1 column
layout:
  Metrics:
    style: row
    columns: 1

theme: dark
color: neutral

favicon: /images/icon_minerva.png

quicklaunch:
    searchDescriptions: true
    hideInternetSearch: true
    hideVisitURL: false

#providers:
#  openweathermap: openweathermapapikey
#  weatherapi: weatherapiapikey

target: _blank
hideVersion: true
language: en