---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings
#

headerStyle: boxed

title: Minerva

background: /images/background_redgalaxy.png
backgroundOpacity: 0.2

layout:
    Home:
        style: columns
        rows: 1
    System:
        style: columns
        rows: 1
    Network:
        style: columns
        rows: 1
    Metrics:
        style: row
        columns: 2
        header: false
#lock Metrics section to 2 columns at the bottom

theme: dark
color: neutral

favicon: /images/icon_minerva.png

quicklaunch:
    searchDescriptions: true
    hideInternetSearch: true
    hideVisitURL: false

#providers:
#  openweathermap: openweathermapapikey
#  weatherapi: weatherapiapikey

target: _blank

hideVersion: true

language: en