---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings
#

title: Minerva
headerStyle: underlined
statusStyle: dot
showStats: true
favicon: /images/icon_minerva.png
logo: /images/icon_minerva.png
background: 
    image: /images/background_redgalaxy.png
    opacity: 0.2
theme: dark
color: gray
quicklaunch:
    searchDescriptions: true
    hideInternetSearch: true
    hideVisitURL: false
target: _blank
hideVersion: true
language: en
#providers:
#  openweathermap: openweathermapapikey
#  weatherapi: weatherapiapikey

layout:
    Minerva:
        style: row
        columns: 6
        useEqualHeights: true
        header: false
    System:
        style: columns
        rows: 2
    Network:
        style: columns
        rows: 2
    Media: 
        style: columns
        rows: 2
#    Metrics:
#        style: row
#        columns: 2
#        header: false
#lock Metrics section to 2 columns at the bottom

