---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings
#

base: https://192.168.1.19:3002

headerStyle: boxed

title: Minerva

background: https://cdn.discordapp.com/attachments/337320584084062208/1098487762681872444/mdh54ilu39g81.png
backgroundOpacity: 0.2

#layout:
#  System:
#    style: row
#    columns: 4

theme: dark
color: neutral

favicon: https://cdn.discordapp.com/attachments/337320584084062208/1098520849436393542/icons8-maxcdn-120.png

quicklaunch:
    searchDescriptions: true
    hideInternetSearch: true
    hideVisitURL: false

#providers:
#  openweathermap: openweathermapapikey
#  weatherapi: weatherapiapikey

target: _blank
hideVersion: true
language: en