version: '3'

services:

  flame:
    image: pawelmalak/flame:latest
    container_name: flame
    volumes:
      - /path/to/host/data:/app/data
      #- /var/run/docker.sock:/var/run/docker.sock # optional but required for Docker integration
    ports:
      - 5005:5005
    #secrets:
    #  - password # optional but required for (1)
    environment:
      - PASSWORD=minervaflame
    #  - PASSWORD_FILE=/run/secrets/password # optional but required for (1)
    restart: unless-stopped

  portainer:
    container_name: portainer
    image: "portainer/portainer-ce:latest"
    ports:
      - "9000:9000/tcp"
    volumes:
      - /opt/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=America/Los_Angeles
    restart: unless-stopped

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080

#create networks
networks:
  network:
    driver: bridge
    name: minerva_network