version: '3'

services:

  #flame:
  #  image: pawelmalak/flame:latest
  #  container_name: flame
  #  volumes:
  #    - /path/to/host/data:/app/data
  #    #- /var/run/docker.sock:/var/run/docker.sock # optional but required for Docker integration
  #  ports:
  #    - 5005:5005
  #  #secrets:
  #  #  - password # optional but required for (1)
  #  environment:
  #    - PASSWORD=minervaflame
  #  #  - PASSWORD_FILE=/run/secrets/password # optional but required for (1)
  #  restart: unless-stopped

  portainer:
    container_name: portainer
    image: "portainer/portainer-ce:latest"
    ports:
      - "9000:9000/tcp"
    volumes:
      - /opt/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=America/Los_Angeles
    restart: unless-stopped

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080

  actual_server:
    image: docker.io/actualbudget/actual-server:latest
    ports:
      # This line makes Actual available at port 5006 of the device you run the server on,
      # i.e. http://localhost:5006. You can change the first number to change the port, if you want.
      - '5006:5006'
    # environment:
      # Uncomment any of the lines below to set configuration options.
      # - ACTUAL_HTTPS_KEY=/data/selfhost.key
      # - ACTUAL_HTTPS_CERT=/data/selfhost.crt
      # - ACTUAL_UPLOAD_FILE_SYNC_SIZE_LIMIT_MB=20
      # - ACTUAL_UPLOAD_SYNC_ENCRYPTED_FILE_SYNC_SIZE_LIMIT_MB=50
      # - ACTUAL_UPLOAD_FILE_SIZE_LIMIT_MB=20
      # See all options and more details at https://actualbudget.github.io/docs/Installing/Configuration
      # !! If you are not using any of these options, remove the 'environment:' tag entirely.
    volumes:
      # Change './actual-data' below to the path to the folder you want Actual to store its data in on your server.
      # '/data' is the path Actual will look for its files in by default, so leave that as-is.
      - /opt/actualbudget:/data
    restart: unless-stopped

  

#create networks
networks:
  network:
    driver: bridge
    name: minerva_network