services:
  web:
    image: itzg/rcon
    environment:
      RWA_USERNAME: admin
      RWA_PASSWORD: admin
      RWA_ADMIN: "TRUE"
      # is referring to the hostname of 'mc' compose service below
      RWA_RCON_HOST: mc
      # needs to match the RCON_PASSWORD configured for the container
      RWA_RCON_PASSWORD: "demo"
    ports:
      - "4326:4326"
      - "4327:4327"
    restart: on-failure
  mc:
    container_name: minecraft-server
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      VERSION: "1.21.5"
      MEMORY: "10240M"
      MAX_PLAYERS: "10"
      MOTD: "...and we're live."
      ICON: "minecraft-config/icon_minerva_64.png"
      TZ: "America/Los_Angeles"
      DIFFICULTY: "2"
      PVP: "false"
      SIMULATION_DISTANCE: "12"
      VIEW_DISTANCE: "12"
      LEVEL: "4-2-25"
      ENABLE_WHITELIST: "true"
      PAUSE_WHEN_EMPTY_SECONDS: "300"
      LOG_TIMESTAMP: "true"
      RCON_PASSWORD: "demo"
    volumes:
      - "/opt/minecraft/data:/data"
    restart: on-failure